#!/usr/bin/env python3
"""Maintain the corpus index and check the skill for internal drift.

    python3 tools/corpus.py index   # regenerate references/corpus-index.md from papers.csv
    python3 tools/corpus.py check   # exit 1 on any drift; run before committing and in CI

`references/corpus/papers.csv` is the single source of truth for the corpus. Standard
library only, so it runs anywhere Python 3.9+ does.
"""

import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "references" / "corpus"
CSV_PATH = CORPUS / "papers.csv"
INDEX_PATH = ROOT / "references" / "corpus-index.md"
SKILL_PATH = ROOT / "SKILL.md"
PLUGIN_PATH = ROOT / ".claude-plugin" / "plugin.json"
CFF_PATH = ROOT / "CITATION.cff"

COLUMNS = ["id", "label", "year", "venue", "archetype", "role", "full_text",
           "method_type", "title", "authors", "doi", "url", "file"]
ABSTRACT_ONLY = "abstract only"

# SKILL.md step 3 greps for these. A file may append a " — gloss" to any of them, and may add
# topical sections of its own, but the canonical prefix must be there for the grep to land.
CANONICAL = ["Structure", "Opening move", "Methods", "Results", "Literature", "Voice",
             "Discussion and limitations", "Data, code and funding",
             "Distinctive moves to borrow", "Related files"]
# Required of every full-text file. Literature, Voice and the availability section are absent
# from some papers' analyses, so they are reported as notes rather than errors.
CORE = ["Structure", "Opening move", "Methods", "Results", "Distinctive moves to borrow"]
# Abstract-only files carry this instead, routing to a full-text exemplar.
ABSTRACT_ROUTE = "Section analysis unavailable"


def load_rows():
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != COLUMNS:
            sys.exit(f"papers.csv columns are {reader.fieldnames}, expected {COLUMNS}")
        return list(reader)


def render_index(rows):
    types = Counter(r["method_type"] for r in rows)
    n_abstract = sum(r["full_text"] == ABSTRACT_ONLY for r in rows)
    out = [
        "# Corpus index",
        "",
        "<!-- Generated by `python3 tools/corpus.py index` from references/corpus/papers.csv."
        " Do not edit by hand. -->",
        "",
        f"The {len(rows)} papers in `references/corpus/`, keyed by the Author YEAR label used "
        "throughout `SKILL.md`, `evidence.md` and `examples.md`. *Archetype* is the `SKILL.md` "
        "§0 category; *Role* is a finer description of what the paper does. "
        "`references/corpus/papers.csv` adds title, authors, DOI and source URL.",
        "",
        "| Label | File | Venue | Archetype | Role | Full text |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        full = "abstract only †" if r["full_text"] == ABSTRACT_ONLY else "yes"
        out.append(f"| {r['label']} | `references/corpus/{r['file']}` | *{r['venue']}* | "
                   f"{r['archetype']} | {r['role']} | {full} |")
    out += [
        "",
        f"† The full text is paywalled with no reachable open-access copy. These {n_abstract} "
        "files are built on the verbatim abstract and the bibliographic record, and say so at "
        "the top. Use them for titles, abstracts and framing; they make no claims about section "
        "structure or results prose.",
        "",
        "## Methodological type",
        "",
        "| Type | Papers |",
        "|---|--:|",
    ]
    out += [f"| {t} | {n} |" for t, n in types.most_common()]
    return "\n".join(out) + "\n"


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None, text
    fields, parent = {}, None
    for line in m.group(1).splitlines():
        if re.match(r"^\s+\S", line) and parent:
            k, _, v = line.strip().partition(":")
            fields.setdefault(parent, {})[k.strip()] = v.strip().strip('"')
        else:
            k, _, v = line.partition(":")
            parent = k.strip()
            if v.strip():
                fields[parent] = v.strip()
    return fields, text[m.end():]


def archetype_table(skill_body):
    """Return {archetype: {label: abstract_only_flag}} from the SKILL.md §0 table."""
    sec = skill_body.split("## 0.", 1)[1].split("\n## ", 1)[0]
    table = {}
    for line in sec.splitlines():
        m = re.match(r"^\| \*\*(.+?)\*\* \| .+? \| (.+?) \|$", line)
        if m:
            table[m.group(1)] = {
                e.replace("†", "").strip(): "†" in e for e in m.group(2).split(",")
            }
    return table


def check():
    errors, notes = [], []
    rows = load_rows()

    # Index is current
    if INDEX_PATH.read_text(encoding="utf-8") != render_index(rows):
        errors.append("references/corpus-index.md is stale: run `python3 tools/corpus.py index`")

    # CSV <-> files
    ids = [r["id"] for r in rows]
    if len(set(ids)) != len(ids):
        errors.append("papers.csv has duplicate ids")
    on_disk = {p.name for p in CORPUS.glob("[0-9][0-9]-*.md")}
    listed = {r["file"] for r in rows}
    for f in sorted(on_disk - listed):
        errors.append(f"{f} is not listed in papers.csv")
    for r in rows:
        path = CORPUS / r["file"]
        if r["file"] not in on_disk:
            errors.append(f"papers.csv lists missing file {r['file']}")
            continue
        if not r["file"].startswith(r["id"] + "-"):
            errors.append(f"{r['file']}: id {r['id']} does not match the filename")
        text = path.read_text(encoding="utf-8")
        if (r["full_text"] == ABSTRACT_ONLY) != ("Basis of this analysis" in text):
            errors.append(f"{r['file']}: full_text={r['full_text']} disagrees with the file's basis note")

        # Canonical headings: SKILL.md step 3 greps for them
        headings = re.findall(r"^## (.+)$", text, re.M)
        abstract_only = r["full_text"] == ABSTRACT_ONLY
        required = [ABSTRACT_ROUTE, "Distinctive moves to borrow"] if abstract_only else CORE
        for want in required:
            if not any(h == want or h.startswith(want + " — ") for h in headings):
                errors.append(f"{r['file']}: no '## {want}' heading (SKILL.md step 3 greps for it)")
        if not abstract_only:
            absent = [c for c in CANONICAL if c not in CORE and c != "Related files"
                      and not any(h == c or h.startswith(c + " — ") for h in headings)]
            if absent:
                notes.append(f"{r['file']}: no section analysis for {', '.join(absent)}")

    # SKILL.md frontmatter (Agent Skills spec)
    skill = SKILL_PATH.read_text(encoding="utf-8")
    fm, body = frontmatter(skill)
    if fm is None:
        errors.append("SKILL.md has no YAML frontmatter")
        fm = {}
    name = fm.get("name", "")
    if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", name) or len(name) > 64:
        errors.append(f"SKILL.md name '{name}' breaks the Agent Skills naming rules")
    if name != ROOT.name:
        print(f"note: skill name '{name}' differs from directory '{ROOT.name}'; "
              "install it under a directory of the same name", file=sys.stderr)
    desc = fm.get("description", "")
    if not 1 <= len(desc) <= 1024:
        errors.append(f"SKILL.md description is {len(desc)} chars (limit 1024)")
    if "license" not in fm:
        errors.append("SKILL.md frontmatter has no license")
    n_lines = skill.count("\n")
    if n_lines > 500:
        errors.append(f"SKILL.md is {n_lines} lines (keep under 500)")

    # Versions agree
    versions = {"SKILL.md metadata.version": fm.get("metadata", {}).get("version")}
    if PLUGIN_PATH.exists():
        versions["plugin.json"] = json.loads(PLUGIN_PATH.read_text())["version"]
    m = re.search(r"^version:\s*['\"]?([^'\"\n]+)", CFF_PATH.read_text(), re.M)
    versions["CITATION.cff"] = m.group(1) if m else None
    if len(set(versions.values())) != 1:
        errors.append(f"versions disagree: {versions}")

    # §0 table <-> papers.csv archetypes and full-text flags
    table = archetype_table(body)
    by_label = {r["label"]: r for r in rows}
    csv_arch = {}
    for r in rows:
        for a in r["archetype"].split("; "):
            csv_arch.setdefault(a, set()).add(r["label"])
    if set(table) != set(csv_arch):
        errors.append(f"§0 archetypes {sorted(set(table) ^ set(csv_arch))} differ from papers.csv")
    for arch, exemplars in table.items():
        if set(exemplars) != csv_arch.get(arch, set()):
            errors.append(f"§0 '{arch}' lists {sorted(exemplars)}, "
                          f"papers.csv has {sorted(csv_arch.get(arch, set()))}")
        for label, dagger in exemplars.items():
            r = by_label.get(label)
            if r and dagger != (r["full_text"] == ABSTRACT_ONLY):
                errors.append(f"§0 '{arch}': {label} † flag disagrees with papers.csv full_text")
        if exemplars and all(exemplars.values()):
            errors.append(f"§0 '{arch}' has no full-text exemplar")

    # Paths named in SKILL.md and links in markdown files resolve
    for p in sorted(set(re.findall(r"`(references/[^`*]+?)`", body))):
        if not (ROOT / p).exists():
            errors.append(f"SKILL.md names missing path {p}")
    for md in ROOT.rglob("*.md"):
        if any(part in {".git", "results", "dist"} for part in md.parts):
            continue
        for target in re.findall(r"\]\(([^)#\s]+)(?:#[^)]*)?\)", md.read_text(encoding="utf-8")):
            if re.match(r"^[a-z]+:", target):
                continue
            if not (md.parent / target).exists():
                errors.append(f"{md.relative_to(ROOT)}: broken link {target}")

    for n in notes:
        print(f"note: {n}", file=sys.stderr)
    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    print(f"{len(errors)} problem(s)" if errors else "ok")
    return 1 if errors else 0


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "index":
        INDEX_PATH.write_text(render_index(load_rows()), encoding="utf-8")
        print(f"wrote {INDEX_PATH.relative_to(ROOT)}")
    elif cmd == "check":
        sys.exit(check())
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
