#!/usr/bin/env python3
"""Maintain the corpus index and check the skill for internal drift.

    python3 tools/corpus.py index   # regenerate corpus-index.md and README's corpus block
    python3 tools/corpus.py check   # exit 1 on any drift; run before committing and in CI

`references/corpus/papers.csv` is the single source of truth for the corpus. Standard
library only, so it runs anywhere Python 3.9+ does.
"""

import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "references" / "corpus"
CSV_PATH = CORPUS / "papers.csv"
INDEX_PATH = ROOT / "references" / "corpus-index.md"
SKILL_PATH = ROOT / "SKILL.md"
PLUGIN_PATH = ROOT / ".claude-plugin" / "plugin.json"
MARKETPLACE_PATH = ROOT / ".claude-plugin" / "marketplace.json"
CFF_PATH = ROOT / "CITATION.cff"
CHANGELOG_PATH = ROOT / "CHANGELOG.md"
README_PATH = ROOT / "README.md"
QUOTES_PATH = ROOT / "docs" / "quote-verification.md"

README_BEGIN = "<!-- corpus:begin — generated by tools/corpus.py index -->"
README_END = "<!-- corpus:end -->"

COLUMNS = ["id", "label", "year", "venue", "archetype", "role", "full_text",
           "method_type", "title", "authors", "doi", "url", "file"]
PUBLISHER_PDF = "publisher pdf"

# SKILL.md step 3 greps for these. A file may append a " — gloss" to any of them, and may add
# topical sections of its own, but the canonical prefix must be there for the grep to land.
CANONICAL = ["Structure", "Opening move", "Methods", "Results", "Literature", "Voice",
             "Discussion and limitations", "Data, code and funding",
             "Distinctive moves to borrow", "Related files"]
# Required of every full-text file. Literature, Voice and the availability section are absent
# from some papers' analyses, so they are reported as notes rather than errors.
CORE = ["Structure", "Opening move", "Methods", "Results", "Distinctive moves to borrow"]


# Files whose "Author YEAR" citations must name a corpus paper, and the exceptions: works cited
# as the source of a rule marked ◆ in SKILL.md, which come from reporting guidelines rather
# than the corpus. Add to this set only when the citation is deliberately outside the corpus.
RULE_FILES = ["SKILL.md", "references/evidence.md", "references/examples.md",
              "references/ml-prediction.md", "references/guidance-papers.md",
              "references/checklist.md"]
EXTERNAL_LABELS = {"Bennett 2012"}
MONTHS = {"January", "February", "March", "April", "May", "June", "July", "August",
          "September", "October", "November", "December"}


def load_rows():
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != COLUMNS:
            sys.exit(f"papers.csv columns are {reader.fieldnames}, expected {COLUMNS}")
        return list(reader)


def render_index(rows):
    types = Counter(r["method_type"] for r in rows)
    n_pdf = sum(r["full_text"] == PUBLISHER_PDF for r in rows)
    out = [
        "# Corpus index",
        "",
        "<!-- Generated by `python3 tools/corpus.py index` from references/corpus/papers.csv."
        " Do not edit by hand. -->",
        "",
        f"The {len(rows)} papers in `references/corpus/`, keyed by the Author YEAR label used "
        "throughout `SKILL.md`, `evidence.md` and `examples.md`. *Archetype* is the `SKILL.md` "
        "§0 category; *Role* is a finer description of what the paper does. "
        "`references/corpus/papers.csv` adds title, authors, DOI and source URL.",
        "",
        "| Label | File | Venue | Archetype | Role | Full text |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        full = "publisher PDF" if r["full_text"] == PUBLISHER_PDF else "open access"
        out.append(f"| {r['label']} | `references/corpus/{r['file']}` | *{r['venue']}* | "
                   f"{r['archetype']} | {r['role']} | {full} |")
    out += [
        "",
        f"Every paper is analysed from its full text. For {n_pdf} of them the full text is "
        "paywalled: the analysis was written from the publisher's PDF and its quotations were "
        "checked against it at the time of writing, so `tools/verify_quotes.py` reports them as "
        "*reviewed* rather than re-checking them on every run (see CONTRIBUTING.md).",
        "",
        "## Methodological type",
        "",
        "| Type | Papers |",
        "|---|--:|",
    ]
    out += [f"| {t} | {n} |" for t, n in types.most_common()]
    return "\n".join(out) + "\n"


def render_readme_block(rows):
    """The facts about the corpus that papers.csv already knows."""
    types = Counter(r["method_type"] for r in rows)
    pdf = [r["label"] for r in rows if r["full_text"] == PUBLISHER_PDF]
    covid = [r for r in rows
             if "covid" in r["title"].lower() or "sars-cov-2" in r["title"].lower()]
    years = sorted(r["year"] for r in rows)
    out = [
        README_BEGIN,
        "",
        f"**{len(rows)} papers spanning {years[0]}–{years[-1]}**, "
        f"{len(covid)} of them on COVID-19.",
        "",
        "| Methodological type | Papers |",
        "|---|--:|",
    ]
    out += [f"| {ty} | {n} |" for ty, n in types.most_common()]
    out += [
        "",
        f"Every paper is analysed from its full text. For {len(pdf)} of them "
        f"({', '.join(pdf)}) that full text is paywalled, so the analysis was written from the "
        "publisher's PDF and its quotations checked against it then rather than on every run.",
    ]
    if QUOTES_PATH.exists():
        m = re.search(r"^\*\*Totals:\*\* (.+?)\.$", QUOTES_PATH.read_text(encoding="utf-8"),
                      re.M)
        if m:
            out += [
                "",
                f"**Quotation coverage:** {m.group(1)} — every quotation of 30 or more "
                "characters checked against the paper's abstract and, where PubMed Central "
                "holds it, the full text (`python3 tools/verify_quotes.py`; report in "
                "[`docs/quote-verification.md`](docs/quote-verification.md)). *Unchecked* "
                "means no open full text was reachable, not that the quotation is wrong.",
            ]
    out += ["", README_END]
    return "\n".join(out)


def splice_readme(block):
    text = README_PATH.read_text(encoding="utf-8")
    start, end = text.find(README_BEGIN), text.find(README_END)
    if start == -1 or end == -1:
        sys.exit(f"README.md has no {README_BEGIN} / {README_END} markers")
    return text[:start] + block + text[end + len(README_END):]


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None, text
    fields, parent = {}, None
    for line in m.group(1).splitlines():
        if re.match(r"^\s+\S", line) and parent:
            k, _, v = line.strip().partition(":")
            fields.setdefault(parent, {})[k.strip()] = v.strip().strip('"')
        else:
            k, _, v = line.partition(":")
            parent = k.strip()
            if v.strip():
                fields[parent] = v.strip()
    return fields, text[m.end():]


def archetype_table(skill_body):
    """Return {archetype: {label: abstract_only_flag}} from the SKILL.md §0 table."""
    sec = skill_body.split("## 0.", 1)[1].split("\n## ", 1)[0]
    table = {}
    for line in sec.splitlines():
        m = re.match(r"^\| \*\*(.+?)\*\* \| .+? \| (.+?) \|$", line)
        if m:
            table[m.group(1)] = {
                e.strip(): False for e in m.group(2).split(",")
            }
    return table


NUMBER_WORDS = ("zero one two three four five six seven eight nine ten eleven twelve thirteen "
                "fourteen fifteen sixteen seventeen eighteen nineteen").split()
TENS = {"twenty": 20, "thirty": 30, "forty": 40, "fifty": 50}


def number(text):
    """An integer from digits ("1,548") or an English number word ("twenty-two")."""
    text = text.lower().replace(",", "")
    if text.isdigit():
        return int(text)
    if text in NUMBER_WORDS:
        return NUMBER_WORDS.index(text)
    tens, _, unit = text.partition("-")
    return TENS.get(tens, -1000) + (NUMBER_WORDS.index(unit) if unit in NUMBER_WORDS else 0)


def check():
    errors, notes = [], []
    rows = load_rows()

    # Index is current
    if INDEX_PATH.read_text(encoding="utf-8") != render_index(rows):
        errors.append("references/corpus-index.md is stale: run `python3 tools/corpus.py index`")

    # CSV <-> files
    ids = [r["id"] for r in rows]
    if len(set(ids)) != len(ids):
        errors.append("papers.csv has duplicate ids")
    # Labels are the Author YEAR form used throughout the rule files, so they must be unique:
    # two papers sharing one label makes every citation of it ambiguous. Disambiguate with a
    # trailing letter, as Bracher 2021a / Bracher 2021b.
    seen = Counter(r["label"] for r in rows)
    for label, n in sorted(seen.items()):
        if n > 1:
            errors.append(f"papers.csv has {n} papers labelled {label!r}; labels must be unique")
    on_disk = {p.name for p in CORPUS.glob("[0-9][0-9]-*.md")}
    listed = {r["file"] for r in rows}
    for f in sorted(on_disk - listed):
        errors.append(f"{f} is not listed in papers.csv")
    for r in rows:
        path = CORPUS / r["file"]
        if r["file"] not in on_disk:
            errors.append(f"papers.csv lists missing file {r['file']}")
            continue
        if not r["file"].startswith(r["id"] + "-"):
            errors.append(f"{r['file']}: id {r['id']} does not match the filename")
        text = path.read_text(encoding="utf-8")
        # Canonical headings: SKILL.md step 3 greps for them
        headings = re.findall(r"^## (.+)$", text, re.M)
        for want in CORE:
            if not any(h == want or h.startswith(want + " — ") for h in headings):
                errors.append(f"{r['file']}: no '## {want}' heading (SKILL.md step 3 greps for it)")
        absent = [c for c in CANONICAL if c not in CORE and c != "Related files"
                  and not any(h == c or h.startswith(c + " — ") for h in headings)]
        if absent:
            notes.append(f"{r['file']}: no section analysis for {', '.join(absent)}")

    # Exemplars of one archetype link each other, in both directions, from `Related files`:
    # a reader who lands on any one of them can reach the rest. Adding a paper therefore means
    # adding a sentence to each sibling's `Related files` saying what the new paper adds.
    by_arch = {}
    for r in rows:
        for arch in r["archetype"].split("; "):
            by_arch.setdefault(arch, []).append(r)
    for arch, members in sorted(by_arch.items()):
        for r in members:
            if r["file"] not in on_disk:
                continue
            text = (CORPUS / r["file"]).read_text(encoding="utf-8")
            m = re.search(r"^## Related files\n(.*?)(?=^## |\Z)", text, re.M | re.S)
            related = m.group(1) if m else ""
            for o in members:
                if o is not r and f"]({o['file']})" not in related:
                    errors.append(f"{r['file']}: Related files does not link {o['label']} "
                                  f"(both are {arch})")

    skill = SKILL_PATH.read_text(encoding="utf-8")

    # SKILL.md's preamble counts match papers.csv
    covid = sum("covid" in r["title"].lower() or "sars-cov-2" in r["title"].lower()
                for r in rows)
    years = sorted(r["year"] for r in rows)
    claims = [
        (r"Rules distilled from (\d+) well-written", str(len(rows)), "paper count"),
        (r"papers \((\d{4})–\d{4};", years[0], "first year"),
        (r"papers \(\d{4}–(\d{4});", years[-1], "last year"),
        (r"(\d+) of \d+ are COVID-19", str(covid), "COVID-19 count"),
        (r"\d+ of (\d+) are COVID-19", str(len(rows)), "COVID-19 denominator"),
    ]
    for pattern, expected, what in claims:
        m = re.search(pattern, skill)
        if not m:
            errors.append(f"SKILL.md preamble: cannot find the {what} "
                          f"(expected it to match /{pattern}/)")
        elif m.group(1) != expected:
            errors.append(f"SKILL.md preamble says {what} is {m.group(1)}, "
                          f"papers.csv says {expected}")

    # The same corpus facts stated elsewhere agree with papers.csv and SKILL.md: the paper count,
    # the number of archetypes (written as a word) and the approximate size of SKILL.md.
    n_arch = len(re.findall(r"^\| \*\*", skill.split("## 0.", 1)[1].split("\n---", 1)[0], re.M))
    skill_lines, skill_words = len(skill.splitlines()), len(skill.split())
    doc_claims = [
        ("README.md", r"style of (\d+) well-written papers", len(rows), "paper count"),
        ("README.md", r"One style analysis per paper \((\d+) files\)", len(rows), "corpus file count"),
        ("CITATION.cff", r"writing style of (\d+) well-written papers", len(rows), "paper count"),
        (".claude-plugin/plugin.json", r"from an? (\d+)-paper corpus", len(rows), "paper count"),
        ("CHANGELOG.md", r"distilled from (\d+) well-written", len(rows), "paper count"),
        ("CHANGELOG.md", r"All (\d+)\s+papers are analysed", len(rows), "paper count"),
        ("README.md", r"— ([a-z-]+) paper types", n_arch, "archetype count"),
        ("CHANGELOG.md", r"\*\*([A-Za-z-]+) paper archetypes\*\*", n_arch, "archetype count"),
    ]
    for name, pattern, expected, what in doc_claims:
        m = re.search(pattern, (ROOT / name).read_text(encoding="utf-8"))
        if not m:
            errors.append(f"{name}: cannot find the {what} (expected it to match /{pattern}/)")
        elif number(m.group(1)) != expected:
            errors.append(f"{name} says the {what} is {m.group(1)}; the corpus has {expected}")
    size_claims = [
        ("README.md", r"~([\d,]+) lines / ~([\d,]+) words"),
        ("CHANGELOG.md", r"\*\*`SKILL.md`\*\*, ~(\d+) lines"),
    ]
    for name, pattern in size_claims:
        m = re.search(pattern, (ROOT / name).read_text(encoding="utf-8"))
        if not m:
            errors.append(f"{name}: cannot find the size of SKILL.md (expected /{pattern}/)")
            continue
        for claimed, actual, unit in zip(m.groups(), (skill_lines, skill_words), ("lines", "words")):
            if abs(number(claimed) - actual) > 0.1 * actual:
                errors.append(f"{name} says SKILL.md is ~{claimed} {unit}; it is {actual}")

    # Every "Author YEAR" citation in the rule files names a corpus paper
    labels = {r["label"] for r in rows}
    cite = re.compile(r"\b([A-Z][a-zø]+(?: & [A-Z][a-zø]+)?) (\d{4})\b")
    for name in RULE_FILES:
        path = ROOT / name
        if not path.exists():
            errors.append(f"{name} is named in RULE_FILES but does not exist")
            continue
        bad = {f"{m.group(1)} {m.group(2)}"
               for m in cite.finditer(path.read_text(encoding="utf-8"))
               if m.group(1) not in MONTHS}
        for label in sorted(bad - labels - EXTERNAL_LABELS):
            errors.append(f"{name} cites '{label}', which is not a label in papers.csv "
                          "(add the paper, fix the typo, or list it in EXTERNAL_LABELS)")

    # README corpus block is current
    block = render_readme_block(rows)
    if README_PATH.read_text(encoding="utf-8") != splice_readme(block):
        errors.append("README.md corpus block is stale: run `python3 tools/corpus.py index`")

    # SKILL.md frontmatter (Agent Skills spec)
    fm, body = frontmatter(skill)
    if fm is None:
        errors.append("SKILL.md has no YAML frontmatter")
        fm = {}
    name = fm.get("name", "")
    if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", name) or len(name) > 64:
        errors.append(f"SKILL.md name '{name}' breaks the Agent Skills naming rules")
    if name != ROOT.name:
        print(f"note: skill name '{name}' differs from directory '{ROOT.name}'; "
              "install it under a directory of the same name", file=sys.stderr)
    desc = fm.get("description", "")
    if not 1 <= len(desc) <= 1024:
        errors.append(f"SKILL.md description is {len(desc)} chars (limit 1024)")
    if "license" not in fm:
        errors.append("SKILL.md frontmatter has no license")
    n_lines = skill.count("\n")
    if n_lines > 500:
        errors.append(f"SKILL.md is {n_lines} lines (keep under 500)")

    # Plugin manifests
    plugin = {}
    if not PLUGIN_PATH.exists():
        errors.append(".claude-plugin/plugin.json is missing")
    else:
        try:
            plugin = json.loads(PLUGIN_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"plugin.json is not valid JSON: {exc}")
        for field in ("name", "version", "description", "license", "author"):
            if not plugin.get(field):
                errors.append(f"plugin.json has no {field}")
        if plugin.get("name") and plugin["name"] != name:
            errors.append(f"plugin.json name '{plugin['name']}' differs from "
                          f"SKILL.md name '{name}'")
        if plugin.get("skills") != ["./"]:
            errors.append(f"plugin.json skills is {plugin.get('skills')!r}, expected ['./'] "
                          "(SKILL.md sits at the repo root)")

    if not MARKETPLACE_PATH.exists():
        errors.append(".claude-plugin/marketplace.json is missing")
    else:
        try:
            market = json.loads(MARKETPLACE_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"marketplace.json is not valid JSON: {exc}")
            market = {}
        if not market.get("name"):
            errors.append("marketplace.json has no name")
        if not (market.get("owner") or {}).get("name"):
            errors.append("marketplace.json has no owner.name")
        listed = market.get("plugins") or []
        if not listed:
            errors.append("marketplace.json lists no plugins")
        for entry in listed:
            for field in ("name", "source", "description"):
                if not entry.get(field):
                    errors.append(f"marketplace.json plugin entry has no {field}")
        if plugin.get("name") and plugin["name"] not in {e.get("name") for e in listed}:
            errors.append(f"marketplace.json does not list the plugin '{plugin['name']}'")

    # Versions agree, and the version has a CHANGELOG section
    versions = {"SKILL.md metadata.version": fm.get("metadata", {}).get("version")}
    if plugin.get("version"):
        versions["plugin.json"] = plugin["version"]
    m = re.search(r"^version:\s*['\"]?([^'\"\n]+)", CFF_PATH.read_text(), re.M)
    versions["CITATION.cff"] = m.group(1) if m else None
    if len(set(versions.values())) != 1:
        errors.append(f"versions disagree: {versions}")
    version = versions["SKILL.md metadata.version"]
    if not CHANGELOG_PATH.exists():
        errors.append("CHANGELOG.md is missing")
    elif version:
        changelog = CHANGELOG_PATH.read_text(encoding="utf-8")
        headings = re.findall(r"^## \[([^\]]+)\]", changelog, re.M)
        if version not in headings:
            errors.append(f"CHANGELOG.md has no '## [{version}]' section "
                          f"(it has {headings or 'none'})")
        elif headings[0] != version:
            errors.append(f"CHANGELOG.md leads with [{headings[0]}], not the current "
                          f"version [{version}]; newest first")

    # §0 table <-> papers.csv archetypes and full-text flags
    table = archetype_table(body)
    by_label = {r["label"]: r for r in rows}
    csv_arch = {}
    for r in rows:
        for a in r["archetype"].split("; "):
            csv_arch.setdefault(a, set()).add(r["label"])
    if set(table) != set(csv_arch):
        errors.append(f"§0 archetypes {sorted(set(table) ^ set(csv_arch))} differ from papers.csv")
    for arch, exemplars in table.items():
        if set(exemplars) != csv_arch.get(arch, set()):
            errors.append(f"§0 '{arch}' lists {sorted(exemplars)}, "
                          f"papers.csv has {sorted(csv_arch.get(arch, set()))}")
        for label in exemplars:
            if label not in by_label:
                errors.append(f"§0 '{arch}' lists unknown label {label!r}")

    # Paths named in SKILL.md and links in markdown files resolve
    for p in sorted(set(re.findall(r"`(references/[^`*]+?)`", body))):
        if not (ROOT / p).exists():
            errors.append(f"SKILL.md names missing path {p}")
    for md in ROOT.rglob("*.md"):
        if any(part in {".git", "results", "dist"} for part in md.parts):
            continue
        for target in re.findall(r"\]\(([^)#\s]+)(?:#[^)]*)?\)", md.read_text(encoding="utf-8")):
            if re.match(r"^[a-z]+:", target):
                continue
            if not (md.parent / target).exists():
                errors.append(f"{md.relative_to(ROOT)}: broken link {target}")

    # SKILL.md numbers only its top-level sections; a §N.M reference to it is stale
    # (the subsections live in evidence.md). Cite `SKILL.md` §N and `evidence.md` §N.M.
    rule_files = [ROOT / "SKILL.md", ROOT / "README.md", ROOT / "CONTRIBUTING.md",
                  *sorted((ROOT / "references").rglob("*.md"))]
    for md in rule_files:
        for n, line in enumerate(md.read_text(encoding="utf-8").splitlines(), 1):
            for ref in re.findall(r"SKILL\.md`?\s+§(\d+\.\d+)", line):
                errors.append(f"{md.relative_to(ROOT)}:{n}: `SKILL.md` §{ref} does not exist "
                              f"— cite `SKILL.md` §{ref.split('.')[0]} and `evidence.md` §{ref}")

    for n in notes:
        print(f"note: {n}", file=sys.stderr)
    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    print(f"{len(errors)} problem(s)" if errors else "ok")
    return 1 if errors else 0


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "index":
        rows = load_rows()
        INDEX_PATH.write_text(render_index(rows), encoding="utf-8")
        README_PATH.write_text(splice_readme(render_readme_block(rows)), encoding="utf-8")
        print(f"wrote {INDEX_PATH.relative_to(ROOT)} and the corpus block in README.md")
    elif cmd == "check":
        sys.exit(check())
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
